/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 blastoise.glb 
Author: jimmyho905 (https://sketchfab.com/jimmyho905)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blastoise-009-sv-6d750f147e38433ab17d3ed5a81b9800
Title: Blastoise 009 SV
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

function Blastoise(props) {
  const { scene } = useGLTF('/models/blastoise.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials['5_pm0009.material01_1_0_0']} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh geometry={nodes.Object_9.geometry} material={materials['5_pm0009.material02_1_0_0']} skeleton={nodes.Object_9.skeleton} />
          <skinnedMesh geometry={nodes.Object_11.geometry} material={materials['5_pm0009.material03_1_0_0']} skeleton={nodes.Object_11.skeleton} />
          <skinnedMesh geometry={nodes.Object_13.geometry} material={materials['5_pm0009.material04_1_0_0']} skeleton={nodes.Object_13.skeleton} />
          <skinnedMesh geometry={nodes.Object_15.geometry} material={materials['5_pm0009_1_0_0']} skeleton={nodes.Object_15.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/blastoise.glb')

export default Blastoise;
