/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bulbasaur.glb 
Author: denisduljaj442 (https://sketchfab.com/denisduljaj442)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-sword-shield-bulbasaur-model-cad7498bdb99429e8094cf205411fe01
Title: Pokemon Sword & Shield Bulbasaur Model
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Bulbasaur(props) {
	const { nodes, materials } = useGLTF("/models/bulbasaur.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 5]}>
				<mesh geometry={nodes.Object_2.geometry} material={materials.pm0001_00_BodyA1} />
				<mesh geometry={nodes.Object_3.geometry} material={materials.pm0001_00_BodyB1} />
				<mesh geometry={nodes.Object_4.geometry} material={materials.pm0001_00_Eye1} />
			</group>
		</group>
	);
}

useGLTF.preload("/models/bulbasaur.glb");

export default Bulbasaur;
