/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 charizard.glb 
Author: jimmyho905 (https://sketchfab.com/jimmyho905)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/charizard-006-sv-661ea62da9b5405fb5b01407dd88bc47
Title: Charizard 006 SV
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

 function Charizard(props) {
  const { scene } = useGLTF('/models/charizard.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[0.016, 0, 0]} scale={100}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_340.geometry} material={materials['body_a.004']} skeleton={nodes.Object_340.skeleton} />
          <skinnedMesh geometry={nodes.Object_341.geometry} material={materials['body_b.005']} skeleton={nodes.Object_341.skeleton} />
          <skinnedMesh geometry={nodes.Object_343.geometry} material={materials['l_eye.006']} skeleton={nodes.Object_343.skeleton} />
          <skinnedMesh geometry={nodes.Object_344.geometry} material={materials['r_eye.006']} skeleton={nodes.Object_344.skeleton} />
          <skinnedMesh geometry={nodes.Object_346.geometry} material={materials['fire.002']} skeleton={nodes.Object_346.skeleton} />
          <skinnedMesh geometry={nodes.Object_348.geometry} material={materials['body_b.005']} skeleton={nodes.Object_348.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/charizard.glb')

export default Charizard;
