/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 charmeleon.glb 
Author: jimmyho905 (https://sketchfab.com/jimmyho905)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/charmeleon-005-sv-069dfe776c8e4805b6c5b6036b4bf96c
Title: Charmeleon 005 SV
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

function Charmeleon(props) {
	const { scene } = useGLTF("/models/charmeleon.glb");
	const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
	const { nodes, materials } = useGraph(clone);
	return (
		<group {...props} dispose={null}>
			<group scale={0.01}>
				<group scale={120}>
					<primitive object={nodes._rootJoint} />
					<skinnedMesh geometry={nodes.Object_59.geometry} material={materials.body} skeleton={nodes.Object_59.skeleton} />
					<skinnedMesh geometry={nodes.Object_60.geometry} material={materials.r_eye} skeleton={nodes.Object_60.skeleton} />
					<skinnedMesh geometry={nodes.Object_61.geometry} material={materials.l_eye} skeleton={nodes.Object_61.skeleton} />
					<skinnedMesh geometry={nodes.Object_63.geometry} material={materials.fire} skeleton={nodes.Object_63.skeleton} />
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/models/charmeleon.glb");

export default Charmeleon;
