/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 charmander.glb 
Author: Forsaken AR Official (https://sketchfab.com/FNAF_AR_Official)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mobile-pokemon-duel-004-charmander-6575671830674925b732a60bd30f55a2
Title: Mobile - Pokemon Duel - 004 - Charmander
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Charmander(props) {
  const { nodes, materials } = useGLTF('/models/charmander.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Default_OBJ} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/charmander.glb')

export default Charmander;
