/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 squirtle.glb 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/squirtle-df11cb9c684e4a5fad6eec86d590774d
Title: Squirtle
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

function Squirtle(props) {
	const { scene } = useGLTF("/models/squirtle.glb");
	const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
	const { nodes, materials } = useGraph(clone);
	return (
		<group {...props} dispose={null}>
			<group scale={0.015}>
				<primitive object={nodes._rootJoint} />
				<skinnedMesh geometry={nodes.Object_6.geometry} material={materials.Material_60} skeleton={nodes.Object_6.skeleton} />
				<skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Material_61} skeleton={nodes.Object_7.skeleton} />
			</group>
		</group>
	);
}

useGLTF.preload("/models/squirtle.glb");

export default Squirtle;
